replicaCount: 1

image:
  repository: qniranjan01/openg2p-registry-core-ui
  tag: develop
  pullPolicy: Always

containerPort: 3000

env:
  NODE_ENV: production
  HOSTNAME: "0.0.0.0"

locales:
  configMapName: ""
