locales:
  configMapName: registry-farmer-extension-locales

env:
  APP_MNEMONIC: registry-ui
  APP_URL: https://registry-farmer.dev.openg2p.org
  BACKEND_API_URL: https://staff-farmer-registry-gen2.dev.openg2p.org
  MASTERDATA_BACKEND_API_URL: https://gen2-master-data.dev.openg2p.org
  PARTNER_IMPORT_EXPORT_ENABLE: "true"
  PARTNER_INGEST_URL: https://partner-family-registry-gen2.play.openg2p.org/partner/ingest_data?data_model=dcivc
  VERIFY_SERVICE_URL: https://registry-farmer.dev.openg2p.org/v1/verify
  VP_CLIENT_ID: did:web:registry-farmer.dev.openg2p.org:v1:verify
  VP_PRESENTATION_ID: 7f3c2a91-bb84-4d1f-9a6e-41c8e5a0d9f2
  VP_PURPOSE: Digital identity verification for registry onboarding
